"""remove testtable3

Revision ID: 836623f53aa5
Revises: b7c608cd7e9c
Create Date: 2023-05-24 22:22:50.756608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '836623f53aa5'
down_revision = 'b7c608cd7e9c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('testtable3')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('testtable3',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('e', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('f', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('g', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='testtable3_pkey')
    )
    # ### end Alembic commands ###
