"""Create Folders Table

Revision ID: ab2c1ee6ebd2
Revises: d67203bd55bf
Create Date: 2023-08-22 14:19:10.917395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab2c1ee6ebd2'
down_revision = 'd67203bd55bf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('folders',
    sa.Column('userid', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parent', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['userid'], ['users.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('folders')
    # ### end Alembic commands ###
