"""add testtable3

Revision ID: b7c608cd7e9c
Revises: 9f4ce0c27e83
Create Date: 2023-05-24 22:19:23.402932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7c608cd7e9c'
down_revision = '9f4ce0c27e83'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('testtable3',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('e', sa.String(length=255), nullable=False),
    sa.Column('f', sa.String(length=255), nullable=False),
    sa.Column('g', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('testtable3')
    # ### end Alembic commands ###
