"""update age data class

Revision ID: d67203bd55bf
Revises: 63edef7d6463
Create Date: 2023-06-07 14:57:16.786374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd67203bd55bf'
down_revision = '63edef7d6463'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
