"""add stored files  table

Revision ID: f89d98403252
Revises: 836623f53aa5
Create Date: 2023-05-24 23:04:35.067026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f89d98403252'
down_revision = '836623f53aa5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storedfiles',
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('filesize', sa.Integer(), nullable=False),
    sa.Column('filetype', sa.String(length=255), nullable=False),
    sa.Column('hash', sa.String(length=255), nullable=False),
    sa.Column('keys', sa.LargeBinary(), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['userid'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('storedfiles')
    # ### end Alembic commands ###
